import {
    ActivityIcon, AppWindowIcon, BellIcon, BinaryIcon, BlocksIcon,
    BotIcon, BoxIcon, BracesIcon, BrainCircuitIcon, CableIcon,
    ChartNoAxesCombinedIcon, CheckCircleIcon, CigaretteIcon, CircuitBoardIcon,
    ClockIcon, CloudIcon, CloudyIcon, CodeIcon, CogIcon, CombineIcon,
    CommandIcon, CompassIcon, ConeIcon, CpuIcon, DatabaseIcon,
    DiffIcon, EclipseIcon, FanIcon, FlameIcon,
    FlashlightIcon, FootprintsIcon, FunctionSquareIcon, GalleryVerticalEndIcon,
    GaugeIcon, GemIcon, GitBranchIcon, GitCompareIcon, GitForkIcon,
    GitGraphIcon, GitMergeIcon, GlobeIcon, GripIcon, HammerIcon,
    HandIcon, HardDriveIcon, HashIcon, HeadphonesIcon, InfinityIcon,
    IterationCwIcon, KeyIcon, LampIcon, LayersIcon, LayoutListIcon,
    LightbulbIcon, LinkIcon, ListChecksIcon, ListTodoIcon, LoaderIcon,
    LockIcon, MagnetIcon, MapIcon, MergeIcon, MessageCircleIcon,
    MicrochipIcon, MicrowaveIcon, MonitorIcon, MoonIcon, MountainIcon,
    MousePointer2Icon, MusicIcon, NavigationIcon, NetworkIcon, BadgePlusIcon,
    NotepadTextIcon, NutIcon, OptionIcon, OrbitIcon, PaintbrushIcon,
    PaletteIcon, PaperclipIcon, PencilIcon, PiIcon, PillIcon,
    PuzzleIcon, PyramidIcon, RabbitIcon, RadarIcon, RadioIcon,
    RatIcon, RepeatIcon, ReplaceIcon, RocketIcon, RouteIcon,
    RssIcon, RulerIcon, ScanIcon, ScanEyeIcon,
    ScreenShareIcon, ServerIcon, SettingsIcon, Share2Icon, ShieldIcon,
    ShipIcon, ShipWheelIcon, ShuffleIcon, SigmaIcon, SirenIcon,
    SlidersIcon, SmartphoneIcon, SparklesIcon, SpeakerIcon,
    SplitIcon, SquareFunctionIcon, SquareMousePointerIcon,
    StarIcon, SunIcon, SwordIcon, TabletsIcon, TagIcon, TargetIcon,
    TerminalIcon, TestTubeIcon, TestTubesIcon, TimerIcon, TornadoIcon,
    ToyBrickIcon, Trash2Icon, TreePineIcon, TriangleIcon, TrophyIcon,
    TurtleIcon, VariableIcon, VenetianMaskIcon, VibrateIcon, VideoIcon,
    WallpaperIcon, WandIcon, WarehouseIcon, WatchIcon,
    WavesIcon, WebhookIcon, WindIcon, WifiIcon, WorkflowIcon, WrenchIcon,
    ZapIcon,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const workflowIcons: LucideIcon[] = [
    ActivityIcon, AppWindowIcon, BellIcon, BinaryIcon, BlocksIcon,
    BotIcon, BoxIcon, BracesIcon, BrainCircuitIcon, CableIcon,
    ChartNoAxesCombinedIcon, CheckCircleIcon, CigaretteIcon, CircuitBoardIcon,
    ClockIcon, CloudIcon, CloudyIcon, CodeIcon, CogIcon, CombineIcon,
    CommandIcon, CompassIcon, ConeIcon, CpuIcon, DatabaseIcon,
    DiffIcon, EclipseIcon, FanIcon, FlameIcon,
    FlashlightIcon, FootprintsIcon, FunctionSquareIcon, GalleryVerticalEndIcon,
    GaugeIcon, GemIcon, GitBranchIcon, GitCompareIcon, GitForkIcon,
    GitGraphIcon, GitMergeIcon, GlobeIcon, GripIcon, HammerIcon,
    HandIcon, HardDriveIcon, HashIcon, HeadphonesIcon, InfinityIcon,
    IterationCwIcon, KeyIcon, LampIcon, LayersIcon, LayoutListIcon,
    LightbulbIcon, LinkIcon, ListChecksIcon, ListTodoIcon, LoaderIcon,
    LockIcon, MagnetIcon, MapIcon, MergeIcon, MessageCircleIcon,
    MicrochipIcon, MicrowaveIcon, MonitorIcon, MoonIcon, MountainIcon,
    MousePointer2Icon, MusicIcon, NavigationIcon, NetworkIcon, BadgePlusIcon,
    NotepadTextIcon, NutIcon, OptionIcon, OrbitIcon, PaintbrushIcon,
    PaletteIcon, PaperclipIcon, PencilIcon, PiIcon, PillIcon,
    PuzzleIcon, PyramidIcon, RabbitIcon, RadarIcon, RadioIcon,
    RatIcon, RepeatIcon, ReplaceIcon, RocketIcon, RouteIcon,
    RssIcon, RulerIcon, ScanIcon, ScanEyeIcon,
    ScreenShareIcon, ServerIcon, SettingsIcon, Share2Icon, ShieldIcon,
    ShipIcon, ShipWheelIcon, ShuffleIcon, SigmaIcon, SirenIcon,
    SlidersIcon, SmartphoneIcon, SparklesIcon, SpeakerIcon,
    SplitIcon, SquareFunctionIcon, SquareMousePointerIcon,
    StarIcon, SunIcon, SwordIcon, TabletsIcon, TagIcon, TargetIcon,
    TerminalIcon, TestTubeIcon, TestTubesIcon, TimerIcon, TornadoIcon,
    ToyBrickIcon, Trash2Icon, TreePineIcon, TriangleIcon, TrophyIcon,
    TurtleIcon, VariableIcon, VenetianMaskIcon, VibrateIcon, VideoIcon,
    WallpaperIcon, WandIcon, WarehouseIcon, WatchIcon,
    WavesIcon, WebhookIcon, WindIcon, WifiIcon, WorkflowIcon, WrenchIcon,
    ZapIcon,
];

export function getRandomWorkflowIcon(): LucideIcon {
    return workflowIcons[Math.floor(Math.random() * workflowIcons.length)];
}
